export interface TranscriptionWord {
  word: string;
  start: number;
  end: number;
  score: number;
}

export interface TranscriptionResult {
  text: string;
  words: TranscriptionWord[];
  audioBlob?: Blob;
}

export interface ITranscriber {
  start(): Promise<void>;
  stop(): Promise<TranscriptionResult>;
}

export class FakeTranscriber implements ITranscriber {
  async start(): Promise<void> {
    console.log("FakeTranscriber: Starting recording...");
  }

  async stop(): Promise<TranscriptionResult> {
    console.log("FakeTranscriber: Stopping and 'transcription'...");
    // Simulate latency
    await new Promise((resolve) => setTimeout(resolve, 1000));
    const text = "This is a fake transcript generated by the Skeleton app. It has enough words to test the Rust metrics.";
    return {
      text,
      words: text.split(' ').map((w, i) => ({
        word: w,
        start: i * 0.5,
        end: (i * 0.5) + 0.4,
        score: Math.random() > 0.8 ? 0.6 : 0.95 
      }))
    };
  }
}
