export interface TranscriptionWord {
  word: string;
  start: number;
  end: number;
  score: number;
}

export interface TranscriptionResult {
  text: string;
  words: TranscriptionWord[];
  audioBlob?: Blob;
}

export interface ITranscriber {
  start(): Promise<void>;
  stop(): Promise<TranscriptionResult>;
}

const FAKE_TRANSCRIPT_TEXT =
  'This is a fake transcript generated by the Skeleton app. It has enough words to test the Rust metrics.';
const SIMULATION_DELAY_MS = 1000;
const WORD_INTERVAL_SECONDS = 0.5;
const WORD_DURATION_SECONDS = 0.4;
const LOW_SCORE_THRESHOLD = 0.8;
const LOW_SCORE = 0.6;
const HIGH_SCORE = 0.95;

function generateFakeWords(text: string): TranscriptionWord[] {
  return text.split(' ').map((word, index) => ({
    word,
    start: index * WORD_INTERVAL_SECONDS,
    end: index * WORD_INTERVAL_SECONDS + WORD_DURATION_SECONDS,
    score: Math.random() > LOW_SCORE_THRESHOLD ? LOW_SCORE : HIGH_SCORE,
  }));
}

export class FakeTranscriber implements ITranscriber {
  async start(): Promise<void> {
    console.log('FakeTranscriber: Starting recording...');
  }

  async stop(): Promise<TranscriptionResult> {
    console.log("FakeTranscriber: Stopping and 'transcription'...");
    await new Promise((resolve) => setTimeout(resolve, SIMULATION_DELAY_MS));
    return {
      text: FAKE_TRANSCRIPT_TEXT,
      words: generateFakeWords(FAKE_TRANSCRIPT_TEXT),
    };
  }
}
