export interface ITranscriber {
  start(): Promise<void>;
  stop(): Promise<string>;
}

export class FakeTranscriber implements ITranscriber {
  async start(): Promise<void> {
    console.log("FakeTranscriber: Starting recording...");
  }

  async stop(): Promise<string> {
    console.log("FakeTranscriber: Stopping and 'transcription'...");
    // Simulate latency
    await new Promise((resolve) => setTimeout(resolve, 1000));
    return "This is a fake transcript generated by the Skeleton app. It has enough words to test the Rust metrics.";
  }
}
